FROM python:slim


# Set the working directory inside the container
# WORKDIR /app

# Install pip (if not already installed)
# RUN apt-get update && apt-get install -y python3-pip

# Copy the requirements file into the container at /app
# COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
# RUN pip install -r requirements.txt

# Expose a port for any services you need to run (if applicable)
# EXPOSE 8000

# Copy the rest of the application code into the container
# COPY . /app/

# Command to run when the container starts
# CMD ["python", "--version"]